### ISSUE TITLE
conman startup doesn't respect PIDFILE argument

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dun/conman#20]
**What steps will reproduce the problem?**

Specify a `PIDFILE` argument in `/etc/sysconfig/conman` or `/etc/init.d/conman`

**What is the expected output? What do you see instead?**

Expect no errors and for pid file to be written to the specified path.

**What version of the software are you using? On what operating system?**

0.2.8-0.pre3.ch5

**Please provide any additional information below.**

I've changed the user to user conman and would like to write to `/var/run/console/conman.pid`. Here's what I see when trying to start conman; you can see it's trying to write to the default location:

```
[root@dtn2:run]# /etc/init.d/conman restart
Starting ConMan: conmand
PIDFILE is /var/run/console/conmand
ERROR:     Unable to open pidfile "/var/run/conman.pid": Permission denied
```

I tried manually specifying the `-pidfile` and `--pidfile` arguments, but those didn't work either.

Original issue reported on code.google.com by `cameron.harr` on 20 Aug 2014 at 11:18

**Comment by dun** [comment]
This was closed by d60e052269ade6e4ec3ebc3fe025ad88c21cc848 which added the `-P <PidFileName>` command-line option to conmand in order to specify the daemon's PID file.

This command-line option is used in the systemd service file to specify the PID file, and it can be added to the `DAEMON_ARGS` variable in the sysvinit script if needed.
