### ISSUE TITLE
debianization

### ISSUE THREAD

**Issue by blue119** [dun/conman#23]
Hi dun,

I am a linuxer and use debian in life and work. I also use the conman in my work to develop our embed device. sometimes, I'd like to introduce the awesome tool conman to my colleague, but the bad thing is there is no debian package.

I guess more people can figure the awesome tool out if there is debian package and in debian package pool. So I tried to promote the conman to debian and make the debian package at http://mentors.debian.net/package/conman

and the debianization you can find at http://anonscm.debian.org/cgit/collab-maint/conman.git/

hopes it can be accepted in debian ASAP. 

I would also like to let your know what I did  and look forward to hearing any suggestion from you.

BR,
yp

**Comment by dun** [comment]
I finally got a chance to look at this...

Re: `debian/patches/0001-fix-script-interpreter-declaration.patch`: Neither `alpha.exp` nor `conman.exp` should be executed directly. Those files are for being source'd in other Expect scripts (like those in the `lib/examples/` directory). The interpreter declaration shouldn't be needed there.

Re: `debian/patches/0002-fix-hyphen-used-as-minus-sign.patch`: I think it should be `"\-\-with\-tcp\-wrappers"` and `"\-\-with\-freeipmi"`. All of the "-" characters need to be escaped in the long-options in order for all of them to be interpreted as minus signs instead of hyphens.

I'm glad to hear you find ConMan useful. I see it's now showing up in sid. Congrats on getting it accepted.
