### ISSUE TITLE
Had a question

### ISSUE THREAD

**Issue by seitzbg** [dun/conman#30]
Does Conman currently use the epoll mechanism or older style ?  

TIA,

**Comment by dun** [comment]
It calls poll() from a single-threaded non-blocking event loop ([`mux_io()`](/dun/conman/blob/8f5bd09162307a23efb8532a95c4e4a562ce30fe/server.c#L738)). Its poll() abstraction is in [tpoll.c](/dun/conman/blob/master/tpoll.c).

**Comment by seitzbg** [comment]
Do you think adding epoll would make it any better for handling a few thousand connections or does the event loop mostly do similar?

**Comment by dun** [comment]
We routinely run it on clusters of a few thousand nodes without issues.  At that scale, a single core may be getting a work-out, but the daemon is responsive and messages aren't getting dropped. conmand will log when it has to overwrite data from its buffers before it has a chance to write it out. Things should be good as long as you're not seeing that message.

Several performance issues were addressed back in 0.2.7 for one of our clusters with ~2300 IPMI SOL consoles. epoll() would help reduce cpu usage, but there are other bottlenecks that would likely need to be addressed along the way. For example, the client-server protocol is rather inefficient. And I think libipmiconsole has some inefficiencies at that scale as well. Also, epoll() is Linux-specific so something like libev or libevent might be a better route.

**Comment by dun** [comment]
Also, the console type will have an impact on scalability and cpu usage. For example, libipmiconsole uses a thread pool and has additional overhead for handling encryption and the like.

**Comment by seitzbg** [comment]
Yep, thanks for the replies!  It is fine once it starts up just takes awhile to connect to everything.

**Comment by dun** [comment]
High cpu usage when conmand starts with thousands of consoles is an artifact of the `poll()` implementation. As connections are getting established, `mux_io()` is having to repeatedly iterate over the list of consoles to check which ones are ready for I/O. Activity should calm down once connections are established. `epoll()` (or equivalent) would help here since it would eliminate the list traversals.

We tend to see the most activity when we reboot (or "bounce") a cluster since that causes a lot of concurrent I/O. As long as you don't see log messages pertaining to overwritten data, you should be ok.
